baseURL = "https://ctx.sh/"
title = "ctx.sh"
theme = "console"

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
